### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'substring')

### ISSUE THREAD

**Issue by Havunen** [infernojs/ts-plugin-inferno#8]
```
 at getVNodeProps (/home/sampo/git/inferno/node_modules/ts-plugin-inferno/dist/index.js:392:39)
    at createVNode (/home/sampo/git/inferno/node_modules/ts-plugin-inferno/dist/index.js:168:26)
    at visitor (/home/sampo/git/inferno/node_modules/ts-plugin-inferno/dist/index.js:56:28)
    at getVNodeChildren (/home/sampo/git/inferno/node_modules/ts-plugin-inferno/dist/index.js:485:29)
    at createVNode (/home/sampo/git/inferno/node_modules/ts-plugin-inferno/dist/index.js:163:35)
    at visitor (/home/sampo/git/inferno/node_modules/ts-plugin-inferno/dist/index.js:54:28)
    at visitNode (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86560:21)
    at visitEachChildOfParenthesizedExpression (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:87238:32)
    at visitEachChild (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86810:35)
    at visitor (/home/sampo/git/inferno/node_modules/ts-plugin-inferno/dist/index.js:75:60)
    at visitNode (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86560:21)
    at visitEachChildOfReturnStatement (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:87475:13)
    at visitEachChild (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86810:35)
    at visitor (/home/sampo/git/inferno/node_modules/ts-plugin-inferno/dist/index.js:75:60)
    at visitArrayWorker (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86622:51)
    at visitNodes2 (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86593:21)
    at visitEachChildOfBlock (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:87396:13)
    at visitEachChild (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86810:35)
    at visitor (/home/sampo/git/inferno/node_modules/ts-plugin-inferno/dist/index.js:75:60)
    at visitNode (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86560:21)
    at visitFunctionBody (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86766:21)
    at visitEachChildOfMethodDeclaration (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86904:13)
    at visitEachChild (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86810:35)
    at visitor (/home/sampo/git/inferno/node_modules/ts-plugin-inferno/dist/index.js:75:60)
    at visitArrayWorker (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86622:51)
    at visitNodes2 (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86593:21)
    at visitEachChildOfClassDeclaration (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:87547:13)
    at visitEachChild (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86810:35)
    at visitor (/home/sampo/git/inferno/node_modules/ts-plugin-inferno/dist/index.js:75:60)
    at visitArrayWorker (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86622:51)
    at visitNodes2 (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86593:21)
    at visitEachChildOfBlock (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:87396:13)
    at visitEachChild (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86810:35)
    at visitor (/home/sampo/git/inferno/node_modules/ts-plugin-inferno/dist/index.js:75:60)
    at visitNode (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86560:21)
    at visitFunctionBody (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86766:21)
    at visitEachChildOfArrowFunction (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:87261:13)
    at visitEachChild (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86810:35)
    at visitor (/home/sampo/git/inferno/node_modules/ts-plugin-inferno/dist/index.js:75:60)
    at visitArrayWorker (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86622:51)
    at visitNodes2 (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86593:21)
    at visitEachChildOfCallExpression (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:87209:13)
    at visitEachChild (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86810:35)
    at visitor (/home/sampo/git/inferno/node_modules/ts-plugin-inferno/dist/index.js:75:60)
    at visitNode (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86560:21)
    at visitEachChildOfExpressionStatement (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:87409:32)
    at visitEachChild (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86810:35)
    at visitor (/home/sampo/git/inferno/node_modules/ts-plugin-inferno/dist/index.js:75:60)
    at visitArrayWorker (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86622:51)
    at visitNodes2 (/home/sampo/git/inferno/node_modules/typescript/lib/typescript.js:86593:21)
```

**Comment by Havunen** [comment]
fixed in 6.0.1
